# Generated by Django 5.2 on 2025-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diagnosistemplate_professionmodel_tagmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='organization_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
