# Generated by Django 5.2 on 2025-04-23 09:59

import core.models.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_initialappointmentwithdoctormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingWithCardiologistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('Приём завершён', 'Приём завершён'), ('Пациент на прием не явился', 'Пациент на прием не явился'), ('Не завершено', 'Не завершено')], default='Приём завершён', max_length=250)),
                ('has_cardio_complaints', models.BooleanField(default=False)),
                ('has_nerve_complaints', models.BooleanField(default=False)),
                ('other_complaints', models.TextField(blank=True, null=True)),
                ('history_of_illness', models.TextField(blank=True, null=True)),
                ('inheritance', models.TextField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('pulse_general', models.IntegerField(blank=True, null=True)),
                ('arterial_high_low', models.CharField(blank=True, max_length=255, null=True)),
                ('arterial_high', models.IntegerField(blank=True, null=True)),
                ('arterial_low', models.IntegerField(blank=True, null=True)),
                ('imt', models.FloatField(blank=True, null=True)),
                ('imt_interpretation', models.FloatField(blank=True, null=True)),
                ('body_figure', models.CharField(choices=[('правильное,', 'правильное,'), ('неправильное,', 'неправильное,'), ('астеник', 'астеник'), ('нормастеник', 'нормастеник'), ('гиперстеник', 'гиперстеник')], default='правильное, нормастеник', max_length=255)),
                ('skin', models.CharField(choices=[('нормальной окраски', 'нормальной окраски'), ('бледные', 'бледные'), ('желтушные', 'желтушные'), ('гиперемированные,', 'гиперемированные,'), ('высыпания', 'высыпания')], default='нормальной окраски', max_length=255)),
                ('sclera_visible_mucosa', models.CharField(choices=[('нормальной окраски', 'нормальной окраски'), ('бледные', 'бледные'), ('желтушные', 'желтушные'), ('гиперемированные,', 'гиперемированные,')], default='нормальной окраски', max_length=255)),
                ('thyroids', models.CharField(choices=[('не увеличена', 'не увеличена'), ('увеличена до', 'увеличена до'), ('0', '0'), ('I', 'I'), ('II ст', 'II ст')], default='не увеличена', max_length=255)),
                ('cervical', models.CharField(choices=[('не увеличены', 'не увеличены'), ('увеличены', 'увеличены'), ('мягкие', 'мягкие'), ('уплотнены при пальпации', 'уплотнены при пальпации'), ('безболезненные', 'безболезненные'), ('болезненные', 'болезненные')], default='не увеличены, мягкие, безболезненные', max_length=255)),
                ('axillary', models.CharField(choices=[('не увеличены', 'не увеличены'), ('увеличены', 'увеличены'), ('мягкие', 'мягкие'), ('уплотнены при пальпации', 'уплотнены при пальпации'), ('безболезненные', 'безболезненные'), ('болезненные', 'болезненные')], default='не увеличены, мягкие, безболезненные', max_length=255)),
                ('inguinal', models.CharField(choices=[('не увеличены', 'не увеличены'), ('увеличены', 'увеличены'), ('мягкие', 'мягкие'), ('уплотнены при пальпации', 'уплотнены при пальпации'), ('безболезненные', 'безболезненные'), ('болезненные', 'болезненные')], default='не увеличены, мягкие, безболезненные', max_length=255)),
                ('pulse_per_min', models.IntegerField(blank=True, null=True)),
                ('pulse', models.CharField(choices=[('ритмичный', 'ритмичный'), ('аритмичный', 'аритмичный'), ('напряжен', 'напряжен'), ('хорошего', 'хорошего'), ('удовлетворительного наполнения и напряжения', 'удовлетворительного наполнения и напряжения')], default='ритмичный', max_length=255)),
                ('fault_of_pulse', models.CharField(default='отсутствует', max_length=255)),
                ('heart_arterial_high', models.IntegerField(blank=True, null=True)),
                ('heart_arterial_low', models.IntegerField(blank=True, null=True)),
                ('left_heart_edges', models.CharField(default='в норме', max_length=255)),
                ('right_heart_edges', models.CharField(default='в норме', max_length=255)),
                ('upper_heart_edges', models.CharField(default='в норме', max_length=255)),
                ('heart_beat', models.CharField(default='в норме', max_length=255)),
                ('heart_tone', models.CharField(choices=[('чистые', 'чистые'), ('ясные', 'ясные'), ('громкие', 'громкие'), ('приглушенные', 'приглушенные'), ('глухие', 'глухие')], default='чистые, ясные', max_length=255)),
                ('i_tone', models.CharField(blank=True, choices=[('ослаблен', 'ослаблен'), ('усилен', 'усилен')], max_length=255, null=True)),
                ('ii_tone', models.CharField(blank=True, choices=[('аорте', 'аорте'), ('легочной артерии', 'легочной артерии')], max_length=255, null=True)),
                ('noise', models.CharField(blank=True, choices=[('аорте', 'аорте'), ('легочной артерии', 'легочной артерии')], max_length=255, null=True)),
                ('arterial_pulse_stop', models.CharField(blank=True, choices=[('отчетливая', 'отчетливая'), ('ослаблена', 'ослаблена'), ('отсутствует', 'отсутствует'), ('слева', 'слева'), ('справа', 'справа')], max_length=255, null=True)),
                ('varicose_veins_of_superficial_veins', models.CharField(choices=[('отсутствует', 'отсутствует'), ('слева', 'слева'), ('справа', 'справа')], default='отсутствует', max_length=255)),
                ('trophic_skin_changes', models.CharField(default='отсутствует', max_length=255)),
                ('chdd_per_minute', models.IntegerField(blank=True, null=True)),
                ('chest_shape', models.CharField(choices=[('правильная', 'правильная'), ('неправильная', 'неправильная'), ('«бочкообразная»', '«бочкообразная»')], default='правильная', max_length=255)),
                ('pulmonary_fields', models.CharField(choices=[('легочный', 'легочный'), ('с коробочным оттенком', 'с коробочным оттенком'), ('укорочение', 'укорочение'), ('притупление', 'притупление')], default='легочный', max_length=255, verbose_name='При сравнительной перкуссии над легочными полями звук')),
                ('auscultation_breathing', models.CharField(choices=[('везикулярное', 'везикулярное'), ('ослабленное', 'ослабленное'), ('жесткое', 'жесткое'), ('бронхиальное', 'бронхиальное')], default='везикулярное,', max_length=255, verbose_name='При аускультации дыхание')),
                ('wheezing', models.CharField(choices=[('отсутствуют', 'отсутствуют'), ('имеются сухие', 'имеются сухие'), ('влажные', 'влажные'), ('крепитирующие', 'крепитирующие')], default='везикулярное,', max_length=255, verbose_name='Хрипы')),
                ('pleural_friction_rub', models.CharField(blank=True, choices=[('шум трения плевры', 'шум трения плевры')], max_length=255, null=True, verbose_name='шум трения плевры')),
                ('cito', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.base.upload_location)),
                ('for_sanatorium_treatment', models.CharField(blank=True, choices=[('Показан', 'Показан'), ('Не показан', 'Не показан'), ('Противопоказан', 'Противопоказан')], max_length=250, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('illness_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardiologist_consulting', to='core.illnesshistory')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
