# Generated by Django 5.2 on 2025-04-27 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_finalappointmentwithdoctormodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentwithondutydoctormodel',
            options={'verbose_name': 'Appointment | Приём у дежурного врача', 'verbose_name_plural': 'Appointment | Приёмы у дежурного врача'},
        ),
        migrations.AlterModelOptions(
            name='appointmentwithondutydoctoronarrivalmodel',
            options={'verbose_name': 'Appointment | Приём у дежурного врача по прибытии', 'verbose_name_plural': 'Appointment | Приёмы у дежурного врача по прибытии'},
        ),
        migrations.AlterModelOptions(
            name='consultingwithcardiologistmodel',
            options={'verbose_name': 'Appointment | Консультация кардиолога', 'verbose_name_plural': 'Appointment | Консультации кардиолога'},
        ),
        migrations.AlterModelOptions(
            name='consultingwithneurologistmodel',
            options={'verbose_name': 'Appointment | Консультация невролога', 'verbose_name_plural': 'Appointment | Консультации невролога'},
        ),
        migrations.AlterModelOptions(
            name='ekgappointmentmodel',
            options={'verbose_name': 'Appointment | Приём на ЭКГ', 'verbose_name_plural': 'Appointment | Приёмы на ЭКГ'},
        ),
        migrations.AlterModelOptions(
            name='finalappointmentwithdoctormodel',
            options={'verbose_name': 'Appointment | Заключительный приём у врача', 'verbose_name_plural': 'Appointment | Заключительные приёмы у врачей'},
        ),
        migrations.AlterModelOptions(
            name='repeatedappointmentwithdoctormodel',
            options={'verbose_name': 'Appointment | Повторный приём у врача', 'verbose_name_plural': 'Appointment | Повторные приёмы у врачей'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='base_price',
            new_name='price',
        ),
        migrations.CreateModel(
            name='MedicalServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.BigIntegerField(default=0)),
                ('state', models.CharField(choices=[('recommended', 'Рекомендовано'), ('assigned', 'Назначено'), ('cancelled', 'Отменено'), ('stopped', 'Остановлено'), ('dispatched', 'Отправлено')], default='assigned', max_length=50)),
                ('consulted_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md_consulted_doctor', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('illness_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_med_services', to='core.illnesshistory')),
                ('medical_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedureServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('recommended', 'Рекомендовано'), ('assigned', 'Назначено'), ('cancelled', 'Отменено'), ('stopped', 'Остановлено'), ('dispatched', 'Отправлено')], default='assigned', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('proceeded_sessions', models.IntegerField(blank=True, default=0, null=True)),
                ('start_date', models.DateField(null=True)),
                ('frequency', models.CharField(choices=[('каждый день', 'каждый день'), ('через день', 'через день')], default='каждый день', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('illness_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_procedures', to='core.illnesshistory')),
                ('medical_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.servicetypemodel'),
        ),
        migrations.CreateModel(
            name='IndividualProcedureSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('session_number', models.PositiveIntegerField(verbose_name='Номер сеанса')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Проведен'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Массажист')),
                ('assigned_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_sessions', to='core.procedureservicemodel', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Индивидуальный сеанс',
                'verbose_name_plural': 'Индивидуальные сеансы',
                'ordering': ['session_number'],
                'unique_together': {('assigned_procedure', 'session_number')},
            },
        ),
    ]
