# Generated by Django 5.2 on 2025-04-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_appointmentwithondutydoctormodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualproceduresessionmodel',
            options={'ordering': ['session_number'], 'verbose_name': 'Основной лист назначений | Индивидуальный сеанс', 'verbose_name_plural': 'Основной лист назначений | Индивидуальные сеансы'},
        ),
        migrations.AlterModelOptions(
            name='procedureservicemodel',
            options={'verbose_name': 'Основной лист назначений | Процедуры', 'verbose_name_plural': 'Основной лист назначений | Процедуры'},
        ),
    ]
