# Generated by Django 5.2 on 2025-05-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_appointmentwithondutydoctormodel_state_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individualproceduresessionmodel',
            unique_together={('assigned_procedure', 'session_number', 'id')},
        ),
    ]
