# Generated by Django 5.2 on 2025-05-01 12:43

import core.models.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assignedlabs_assignedlabresult_labresultvalue_and_more'),
    ]

    operations = [
        # No operations needed - all changes already in 0016
    ]
