# Generated by Django 5.2 on 2025-05-03 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_companymodel_itemsmodel_warehouse_itemsinstockmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsInStockModel',
            new_name='MedicationsInStockModel',
        ),
        migrations.CreateModel(
            name='MedicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('in_pack', models.PositiveIntegerField(default=10, help_text='Number of units in a standard package')),
                ('unit', models.CharField(choices=[('tablet', 'Таблетки'), ('capsule', 'Капсулы'), ('ml', 'Миллилитры'), ('mg', 'Миллиграммы'), ('g', 'Граммы'), ('piece', 'Штуки'), ('ampule', 'Ампулы'), ('vial', 'Флаконы'), ('patch', 'Пластыри'), ('supp', 'Суппозитории')], default='tablet', max_length=20)),
                ('batch_number', models.CharField(blank=True, help_text='Batch or serial number', max_length=50)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('dosage_form', models.CharField(blank=True, help_text='E.g., tablet, liquid, cream', max_length=50)),
                ('active_ingredients', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.companymodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='medicationsinstockmodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_stock', to='core.medicationmodel'),
        ),
        migrations.CreateModel(
            name='PrescribedMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.CharField(help_text="Dose amount (e.g., '500mg', '2 tablets')", max_length=50)),
                ('frequency', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('bid', 'Два раза в день'), ('tid', 'Три раза в день'), ('qid', 'Четыре раза в день'), ('qhs', 'Перед сном'), ('q4h', 'Каждые 4 часа'), ('q6h', 'Каждые 6 часов'), ('q8h', 'Каждые 8 часов'), ('q12h', 'Каждые 12 часов'), ('weekly', 'Еженедельно'), ('biweekly', 'Два раза в неделю'), ('monthly', 'Ежемесячно'), ('prn', 'По необходимости')], max_length=20)),
                ('route', models.CharField(blank=True, help_text='Route of administration (e.g., oral, IV, topical)', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duration in days (optional)', null=True)),
                ('status', models.CharField(choices=[('recommended', 'Рекомендовано'), ('prescribed', 'Назначено'), ('active', 'Активно'), ('completed', 'Завершено'), ('discontinued', 'Прекращено')], default='prescribed', max_length=20)),
                ('is_prn', models.BooleanField(default=False, help_text='Medication to be taken as needed')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for administration')),
                ('reason', models.TextField(blank=True, help_text='Reason for prescription')),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('illness_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='core.illnesshistory')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.medicationmodel')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('administered_at', models.DateTimeField()),
                ('dosage_given', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('patient_response', models.TextField(blank=True, help_text='How patient responded to medication')),
                ('side_effects', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('prescribed_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='core.prescribedmedication')),
            ],
            options={
                'ordering': ['-administered_at'],
            },
        ),
        migrations.DeleteModel(
            name='ItemsModel',
        ),
        migrations.AddIndex(
            model_name='medicationmodel',
            index=models.Index(fields=['name'], name='core_medica_name_a346dc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationmodel',
            index=models.Index(fields=['expiry_date'], name='core_medica_expiry__d27d86_idx'),
        ),
        migrations.AddIndex(
            model_name='prescribedmedication',
            index=models.Index(fields=['status'], name='core_prescr_status_9d8d12_idx'),
        ),
        migrations.AddIndex(
            model_name='prescribedmedication',
            index=models.Index(fields=['start_date'], name='core_prescr_start_d_c33e59_idx'),
        ),
        migrations.AddIndex(
            model_name='prescribedmedication',
            index=models.Index(fields=['end_date'], name='core_prescr_end_dat_859ecb_idx'),
        ),
    ]
