# Generated by Django 5.2 on 2025-05-03 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_itemsinstockmodel_medicationsinstockmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.medicationsinstockmodel'),
        ),
    ]
