# Generated by Django 5.2 on 2025-05-11 09:58

import core.models.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_prescribedmedication_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.models.base.upload_documents_location)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('medical_results', 'Результаты исследований'), ('consents', 'Согласия'), ('reports', 'Отчеты'), ('other', 'Прочее')], default='other', max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('illness_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.illnesshistory')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
