# Generated by Django 5.2 on 2025-05-17 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('session_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает выдачи'), ('administered', 'Выдано'), ('missed', 'Пропущено'), ('refused', 'Отказано'), ('canceled', 'Отменено')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('prescribed_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.prescribedmedication')),
            ],
            options={
                'ordering': ['session_datetime'],
            },
        ),
        migrations.DeleteModel(
            name='MedicationAdministration',
        ),
        migrations.AddIndex(
            model_name='medicationsession',
            index=models.Index(fields=['session_datetime'], name='core_medica_session_4243df_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationsession',
            index=models.Index(fields=['status'], name='core_medica_status_4b7f68_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationsession',
            index=models.Index(fields=['prescribed_medication', 'session_datetime'], name='core_medica_prescri_00f1d0_idx'),
        ),
    ]
