# Generated by Django 5.2 on 2025-05-21 05:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_individualproceduresessionmodel_scheduled_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualproceduresessionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Проведен'), ('canceled', 'Отменен'), ('conflicted', 'конфликтный')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('bill_amount', models.BigIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(choices=[('в ожидании', 'в ожидании'), ('принято', 'принято'), ('отказано', 'отказано')], default='принято', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.companymodel')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('nds', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('overall_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicationmodel')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_items', to='core.incomemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
