# Generated by Django 5.2 on 2025-07-06 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_individualproceduresessionmodel_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='companymodel',
            options={'verbose_name': 'Warehouses | Company', 'verbose_name_plural': 'Warehouses | Company'},
        ),
        migrations.AlterModelOptions(
            name='incomeitemsmodel',
            options={'verbose_name': 'Warehouses | Income Registry Item', 'verbose_name_plural': 'Warehouses | Income Registry Item'},
        ),
        migrations.AlterModelOptions(
            name='incomemodel',
            options={'verbose_name': 'Warehouses | Income', 'verbose_name_plural': 'Warehouses | Income'},
        ),
        migrations.AlterModelOptions(
            name='medicationmodel',
            options={'ordering': ['name'], 'verbose_name': 'Warehouses | Medications', 'verbose_name_plural': 'Warehouses | Medications'},
        ),
        migrations.AlterModelOptions(
            name='medicationsinstockmodel',
            options={'ordering': ('expire_date',), 'verbose_name': 'Warehouses | In Stock Medication', 'verbose_name_plural': 'Warehouses | In Stock Medication'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Warehouses | Warehouse', 'verbose_name_plural': 'Warehouses | Warehouse'},
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.region'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.region'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
    ]
