# Generated by Django 5.2 on 2025-07-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_district_region_alter_companymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set(),
        ),
    ]
