# Generated by Django 5.2 on 2025-07-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_district_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
