# Generated by Django 5.2 on 2025-09-21 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_patientmodel_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('checked_in', 'Заселен'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('discharged', 'Выписан')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tariff_base_amount', models.IntegerField(default=0, help_text='Base amount from the tariff package')),
                ('additional_services_amount', models.IntegerField(default=0, help_text='Amount for services not included in tariff or exceeding included quantities')),
                ('medications_amount', models.IntegerField(default=0, help_text='Total amount for prescribed medications')),
                ('lab_research_amount', models.IntegerField(default=0, help_text='Total amount for laboratory research and tests')),
                ('total_amount', models.IntegerField(default=0, help_text='Total billing amount (sum of all components)')),
                ('billing_status', models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Calculated'), ('invoiced', 'Invoiced')], default='pending', help_text='Current status of the billing calculation', max_length=20)),
                ('booking', models.OneToOneField(help_text='Reference to the booking this billing record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='core.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Billing',
                'verbose_name_plural': 'Booking Billings',
                'db_table': 'booking_billing',
            },
        ),
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('cash', 'Наличка'), ('payme', 'PayMe'), ('click', 'Click'), ('card', 'Банковская карта'), ('transfer', 'Банковский перевод'), ('humo', 'Humo'), ('uzcard', 'UzCard')], default='cash', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.patientmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ServiceSessionTracking',
        ),
        migrations.AddIndex(
            model_name='bookingbilling',
            index=models.Index(fields=['booking'], name='idx_billing_booking'),
        ),
        migrations.AddIndex(
            model_name='bookingbilling',
            index=models.Index(fields=['billing_status'], name='idx_billing_status'),
        ),
        migrations.AddIndex(
            model_name='bookingbilling',
            index=models.Index(fields=['created_at'], name='idx_billing_calculated'),
        ),
    ]
