# Generated by Django 5.2 on 2025-10-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tariff_price_alter_booking_status_bookingbilling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
