# Generated by Django 5.2 on 2025-10-20 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_medicationsinstockmodel_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('state', models.CharField(choices=[('в ожидании', 'в ожидании'), ('принято', 'принято'), ('отказано', 'отказано')], default='в ожидании', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='core.warehouse')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouses | Transfer',
                'verbose_name_plural': 'Warehouses | Transfers',
            },
        ),
        migrations.CreateModel(
            name='TransferItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('overall_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('income_seria', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicationmodel')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='core.transfermodel')),
            ],
            options={
                'verbose_name': 'Warehouses | Transfer Item',
                'verbose_name_plural': 'Warehouses | Transfer Items',
            },
        ),
    ]
