# Generated by Django 5.2 on 2025-10-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_transfermodel_transferitemsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitemsmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicationsinstockmodel'),
        ),
    ]
