# Generated by Django 5.2 on 2025-10-20 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_transferitemsmodel_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('state', models.CharField(choices=[('в ожидании', 'в ожидании'), ('принято', 'принято'), ('отказано', 'отказано'), ('возвращено', 'возвращено')], default='в ожидании', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('treatment_period', models.CharField(blank=True, help_text='Period for which medications are provided', max_length=255, null=True)),
                ('expected_return_date', models.DateField(blank=True, help_text='Expected date for unused medications to be returned', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_account_transfers', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouses | Account Transfer',
                'verbose_name_plural': 'Warehouses | Account Transfers',
            },
        ),
        migrations.CreateModel(
            name='AccountTransferItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('overall_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('income_seria', models.CharField(blank=True, max_length=255, null=True)),
                ('used_quantity', models.IntegerField(default=0, help_text='Quantity used by the account')),
                ('used_unit_quantity', models.IntegerField(default=0, help_text='Unit quantity used by the account')),
                ('returned_quantity', models.IntegerField(default=0, help_text='Quantity returned to the warehouse')),
                ('returned_unit_quantity', models.IntegerField(default=0, help_text='Unit quantity returned to the warehouse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicationsinstockmodel')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='core.accounttransfermodel')),
            ],
            options={
                'verbose_name': 'Warehouses | Account Transfer Item',
                'verbose_name_plural': 'Warehouses | Account Transfer Items',
            },
        ),
    ]
