# Generated by Django 5.2 on 2025-10-26 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_accounttransfermodel_accounttransferitemsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSessionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sessions_included', models.PositiveIntegerField(default=0, help_text='Number of sessions included in tariff for this period')),
                ('sessions_used', models.PositiveIntegerField(default=0, help_text='Number of sessions actually used in this period')),
                ('sessions_billed', models.PositiveIntegerField(default=0, help_text='Number of sessions that were charged (beyond included amount)')),
            ],
            options={
                'verbose_name': 'Service Session Tracking',
                'verbose_name_plural': 'Service Session Trackings',
            },
        ),
        migrations.AlterModelOptions(
            name='bookingdetail',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='effective_from',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this tariff/room combination started', null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='effective_to',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this tariff/room combination ended', null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True, help_text='Is this the current active tariff/room?'),
        ),
        migrations.AddField(
            model_name='individualproceduresessionmodel',
            name='billed_amount',
            field=models.IntegerField(default=0, help_text='Amount charged for this session', verbose_name='Сумма к оплате'),
        ),
        migrations.AddField(
            model_name='individualproceduresessionmodel',
            name='booking_detail_at_time',
            field=models.ForeignKey(blank=True, help_text='BookingDetail that was active when this session was completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_sessions', to='core.bookingdetail', verbose_name='Тариф на момент проведения'),
        ),
        migrations.AddField(
            model_name='individualproceduresessionmodel',
            name='is_billable',
            field=models.BooleanField(default=False, help_text='Should this session be charged?', verbose_name='Платная сессия'),
        ),
        migrations.AddIndex(
            model_name='bookingdetail',
            index=models.Index(fields=['booking', 'client', 'effective_from'], name='idx_booking_client_eff'),
        ),
        migrations.AddIndex(
            model_name='bookingdetail',
            index=models.Index(fields=['booking', 'is_current'], name='idx_booking_is_current'),
        ),
        migrations.AddIndex(
            model_name='individualproceduresessionmodel',
            index=models.Index(fields=['booking_detail_at_time', 'is_billable'], name='idx_session_billing'),
        ),
        migrations.AddIndex(
            model_name='individualproceduresessionmodel',
            index=models.Index(fields=['status', 'completed_at'], name='idx_session_status_date'),
        ),
        migrations.AddField(
            model_name='servicesessiontracking',
            name='booking_detail',
            field=models.ForeignKey(help_text='The BookingDetail period this tracking belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='service_tracking', to='core.bookingdetail'),
        ),
        migrations.AddField(
            model_name='servicesessiontracking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicesessiontracking',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicesessiontracking',
            name='service',
            field=models.ForeignKey(help_text='The service being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='session_tracking', to='core.service'),
        ),
        migrations.AddField(
            model_name='servicesessiontracking',
            name='tariff_service',
            field=models.ForeignKey(help_text="Reference to the tariff's service configuration", on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='core.tariffservice'),
        ),
        migrations.AddIndex(
            model_name='servicesessiontracking',
            index=models.Index(fields=['booking_detail', 'service'], name='idx_tracking_bd_service'),
        ),
        migrations.AlterUniqueTogether(
            name='servicesessiontracking',
            unique_together={('booking_detail', 'service')},
        ),
    ]
