# Generated by Django 5.2.8 on 2025-12-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_servicesessiontracking_alter_bookingdetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medicationmodel',
            name='core_medica_expiry__d27d86_idx',
        ),
        migrations.RemoveField(
            model_name='medicationmodel',
            name='expiry_date',
        ),
    ]
