# Generated by Django 5.2.8 on 2025-12-06 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_medicationmodel_core_medica_expiry__d27d86_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('expired', 'Истек срок годности'), ('damaged', 'Повреждено'), ('charity', 'Благотворительность'), ('ambulance', 'Скорая помощь'), ('lost', 'Утеряно'), ('other', 'Другое')], help_text='Reason for write-off', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Number of full packs')),
                ('unit_quantity', models.PositiveIntegerField(default=0, help_text='Number of individual units')),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, help_text='Additional details about the expense')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(help_text='Stock item being written off', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.medicationsinstockmodel')),
            ],
            options={
                'verbose_name': 'Warehouses | Medication Expense',
                'verbose_name_plural': 'Warehouses | Medication Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='core_medica_expense_102160_idx'), models.Index(fields=['expense_type'], name='core_medica_expense_39eb51_idx')],
            },
        ),
    ]
