# Generated by Django 5.2.8 on 2025-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_medicationexpensemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodel',
            name='state',
            field=models.CharField(choices=[('в ожидании', 'в ожидании'), ('принято', 'принято'), ('отказано', 'отказано')], default='в ожидании', max_length=50),
        ),
    ]
