# Generated by Django 5.2.8 on 2025-12-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_assignedlab_state_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedlabresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assignedlabs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactionsmodel',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='billing',
            field=models.ForeignKey(blank=True, help_text='Reference to the billing record for this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bookingbilling'),
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the transaction', null=True),
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='reference_number',
            field=models.CharField(blank=True, help_text='External transaction reference (card, PayMe, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В обработке'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка'), ('REFUNDED', 'Возвращено')], default='COMPLETED', help_text='Status of the transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingbilling',
            name='billing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Calculated'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='pending', help_text='Current status of the billing calculation', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transactionsmodel',
            index=models.Index(fields=['booking'], name='idx_trans_booking'),
        ),
        migrations.AddIndex(
            model_name='transactionsmodel',
            index=models.Index(fields=['billing'], name='idx_trans_billing'),
        ),
        migrations.AddIndex(
            model_name='transactionsmodel',
            index=models.Index(fields=['status'], name='idx_trans_status'),
        ),
        migrations.AddIndex(
            model_name='transactionsmodel',
            index=models.Index(fields=['created_at'], name='idx_trans_created'),
        ),
        migrations.AlterModelTable(
            name='transactionsmodel',
            table='transactions',
        ),
    ]
