# Generated by Django 5.2.8 on 2025-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_payment_processing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationmodel',
            name='unit_price',
            field=models.IntegerField(
                default=0,
                help_text="Standard unit price for billing calculations"
            ),
        ),
    ]
