# Generated by Django 5.2.8 on 2025-12-09 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_checkinlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма депозита', max_digits=10)),
                ('deposit_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Процент от общей стоимости (если применимо)', max_digits=5, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн оплата')], help_text='Способ оплаты депозита', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('paid', 'Оплачен'), ('refunded', 'Возвращен'), ('forfeited', 'Аннулирован')], db_index=True, default='pending', help_text='Статус депозита', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Когда был оплачен депозит', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='Когда был возвращен депозит', null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Сумма возврата (может отличаться от суммы депозита)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Примечания к депозиту', null=True)),
                ('receipt_number', models.CharField(blank=True, db_index=True, help_text='Номер квитанции об оплате', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Booking Deposit',
                'verbose_name_plural': 'Booking Deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Создано'), ('status_changed', 'Изменен статус'), ('dates_changed', 'Изменены даты'), ('tariff_changed', 'Изменен тариф'), ('room_changed', 'Изменена комната'), ('guest_added', 'Добавлен гость'), ('guest_removed', 'Удален гость'), ('service_added', 'Добавлена услуга'), ('service_removed', 'Удалена услуга'), ('service_session_recorded', 'Записана сессия услуги'), ('notes_updated', 'Обновлены примечания'), ('other', 'Другое')], db_index=True, help_text='Тип выполненного действия', max_length=50)),
                ('field_name', models.CharField(blank=True, help_text='Название измененного поля (если применимо)', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Предыдущее значение', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Новое значение', null=True)),
                ('description', models.TextField(blank=True, help_text='Описание изменения', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Когда было сделано изменение')),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Плановое обслуживание'), ('deep_cleaning', 'Глубокая уборка'), ('repair', 'Ремонт'), ('inspection', 'Проверка'), ('renovation', 'Ремонт помещения'), ('other', 'Другое')], db_index=True, help_text='Тип обслуживания', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='scheduled', help_text='Статус обслуживания', max_length=20)),
                ('start_date', models.DateTimeField(db_index=True, help_text='Начало обслуживания')),
                ('end_date', models.DateTimeField(db_index=True, help_text='Окончание обслуживания')),
                ('description', models.TextField(blank=True, help_text='Описание работ по обслуживанию', null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Расчетная стоимость обслуживания', max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Фактическая стоимость обслуживания', max_digits=10, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Когда обслуживание было завершено', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Примечания о завершении обслуживания', null=True)),
            ],
            options={
                'verbose_name': 'Room Maintenance',
                'verbose_name_plural': 'Room Maintenance Records',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('desired_start_date', models.DateTimeField(db_index=True, help_text='Желаемая дата начала')),
                ('desired_end_date', models.DateTimeField(db_index=True, help_text='Желаемая дата окончания')),
                ('number_of_guests', models.PositiveSmallIntegerField(default=1, help_text='Количество гостей')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], db_index=True, default='normal', help_text='Приоритет запроса', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('contacted', 'Связались'), ('converted', 'Преобразован в бронирование'), ('expired', 'Истек'), ('cancelled', 'Отменен')], db_index=True, default='active', help_text='Статус записи в листе ожидания', max_length=20)),
                ('contacted_at', models.DateTimeField(blank=True, help_text='Когда связались с клиентом', null=True)),
                ('converted_at', models.DateTimeField(blank=True, help_text='Когда был преобразован в бронирование', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Когда истекает запрос (авто-расчет)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Примечания к запросу', null=True)),
                ('contact_preference', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('sms', 'SMS'), ('any', 'Любой')], default='phone', help_text='Предпочтительный способ связи', max_length=20)),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='checkinlog',
            options={'ordering': ['-check_in_time'], 'verbose_name': 'Check-in Log', 'verbose_name_plural': 'Check-in Logs'},
        ),
        # migrations.RemoveIndex(
        #     model_name='assignedlabs',
        #     name='core_assign_state_13efd7_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='assignedlabs',
        #     name='core_assign_lab_tes_eea3cc_idx',
        # ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reservation', 'Резервация'), ('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('checked_in', 'Заселен'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('discharged', 'Выписан')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkinlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkinlog',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='idx_booking_number'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_booking_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_booking_dates'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['staff'], name='idx_booking_staff'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='idx_booking_created'),
        ),
        migrations.AddIndex(
            model_name='patientmodel',
            index=models.Index(fields=['f_name', 'l_name'], name='idx_patient_name'),
        ),
        migrations.AddIndex(
            model_name='patientmodel',
            index=models.Index(fields=['mobile_phone_number'], name='idx_patient_mobile'),
        ),
        migrations.AddIndex(
            model_name='patientmodel',
            index=models.Index(fields=['email'], name='idx_patient_email'),
        ),
        migrations.AddIndex(
            model_name='patientmodel',
            index=models.Index(fields=['date_of_birth'], name='idx_patient_dob'),
        ),
        migrations.AddIndex(
            model_name='patientmodel',
            index=models.Index(fields=['region', 'district'], name='idx_patient_location'),
        ),
        migrations.AddIndex(
            model_name='patientmodel',
            index=models.Index(fields=['is_active'], name='idx_patient_active'),
        ),
        migrations.AddIndex(
            model_name='patientmodel',
            index=models.Index(fields=['-created_at'], name='idx_patient_created'),
        ),
        migrations.AddField(
            model_name='bookingdeposit',
            name='booking',
            field=models.OneToOneField(help_text='Бронирование, к которому относится депозит', on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='core.booking'),
        ),
        migrations.AddField(
            model_name='bookingdeposit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingdeposit',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingdeposit',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Сотрудник, обработавший депозит', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='booking',
            field=models.ForeignKey(help_text='Бронирование, к которому относится запись истории', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.booking'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='booking_detail',
            field=models.ForeignKey(blank=True, help_text='Конкретная деталь бронирования (если применимо)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='core.bookingdetail'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='changed_by',
            field=models.ForeignKey(help_text='Пользователь, который внес изменение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommaintenance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Сотрудник, назначенный на обслуживание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_maintenance_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommaintenance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommaintenance',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommaintenance',
            name='room',
            field=models.ForeignKey(help_text='Комната, находящаяся на обслуживании', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.room'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='contacted_by',
            field=models.ForeignKey(blank=True, help_text='Кто связался с клиентом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='converted_booking',
            field=models.ForeignKey(blank=True, help_text='Бронирование, созданное из листа ожидания', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_source', to='core.booking'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='created_by',
            field=models.ForeignKey(help_text='Кто создал запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='desired_room_type',
            field=models.ForeignKey(blank=True, help_text='Желаемый тип комнаты', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.roomtype'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='desired_tariff',
            field=models.ForeignKey(blank=True, help_text='Желаемый тариф', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.tariff'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='patient',
            field=models.ForeignKey(help_text='Пациент в листе ожидания', on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.patientmodel'),
        ),
        migrations.AddIndex(
            model_name='bookingdeposit',
            index=models.Index(fields=['booking'], name='idx_deposit_booking'),
        ),
        migrations.AddIndex(
            model_name='bookingdeposit',
            index=models.Index(fields=['status'], name='idx_deposit_status'),
        ),
        migrations.AddIndex(
            model_name='bookingdeposit',
            index=models.Index(fields=['paid_at'], name='idx_deposit_paid_at'),
        ),
        migrations.AddIndex(
            model_name='bookingdeposit',
            index=models.Index(fields=['receipt_number'], name='idx_deposit_receipt'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['booking', '-changed_at'], name='idx_booking_hist_date'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['booking', 'action'], name='idx_booking_hist_action'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['changed_by', '-changed_at'], name='idx_booking_hist_user'),
        ),
        migrations.AddIndex(
            model_name='roommaintenance',
            index=models.Index(fields=['room', 'start_date', 'end_date'], name='idx_maintenance_room_dates'),
        ),
        migrations.AddIndex(
            model_name='roommaintenance',
            index=models.Index(fields=['status', 'start_date'], name='idx_maintenance_status_date'),
        ),
        migrations.AddIndex(
            model_name='roommaintenance',
            index=models.Index(fields=['maintenance_type'], name='idx_maintenance_type'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='idx_waitlist_status_priority'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['desired_start_date', 'desired_end_date'], name='idx_waitlist_dates'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['patient'], name='idx_waitlist_patient'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['expires_at'], name='idx_waitlist_expires'),
        ),
    ]
