from .base import *
from .account import *
from .booking import *
from .clients import *
from .notifications import *
from .rooms import *
from .services import *
from .tariffs import *
from .illness_history import *
from .lab_research import *
from .sanatorium import *
from .documents import *
from .warehouse import *
from .transactions import *